### ISSUE TITLE
always EXC_BAD_Access while accessing uitextfield

### ISSUE THREAD

**Issue by romin991** [kif-framework/KIF#701] opened 2015-08-13 10:15 UTC
hello, i don't know what's wrong with my code... 
i've created simple project and it doesn't crash.

but when i implement it in my existing project, it always crash....

on this : [[UIApplication sharedApplication] sendEvent:event]; 

my code is simple...

[tester waitForViewWithAccessibilityLabel:@"Start View"];
    [tester tapViewWithAccessibilityLabel:@"Create Account Button"];

    [tester waitForViewWithAccessibilityLabel:@"Account Register View"];
    [tester enterText:@"lsdj" intoViewWithAccessibilityLabel:@"fieldku"];

always crash when i enterText to a textfield.... if i set the accessibility label wrongly, it won't crash.. but it will timeout 10s..

please help! thx!

**Comment by phatmann** [comment] 2015-08-13 15:14
Thanks for the report. This a duplicate of #698. I will try and get it fixed ASAP.

**Closed by phatmann** 2015-08-13 15:14 UTC
