### ISSUE TITLE
framework not found KIF

### ISSUE THREAD

**Issue by ohadnav** [kif-framework/KIF#992] opened 2017-08-06 06:40 UTC
Everything plays out well on the simulator, but somehow test build fails on a real device (using the stable version of KIF)

> ld: framework not found KIF

**Comment by justinseanmartin** [comment] 2017-08-07 19:00
That sounds like a project configuration issue most likely. Are you using CocoaPods to consume KIF as a dynamic framework?

Some ideas for debugging:
* Make sure the `LD_RUNPATH_SEARCH_PATHS` setting has `@executable_path/Frameworks' '@loader_path/Frameworks`.
* Open up your `.xctest` bundle being produced in the derived data folder and make sure it contains `KIF.framework` in there.

**Comment by ohadnav** [comment] 2017-08-07 20:47
I am using cocoa pods, both paths are found in `LD_RUNPATH_SEARCH_PATHS `. I have found `KIF.framework` under /.../DerivedData/App/Build/Products/Debug-iphones/KIF/KIF.framework

Some more data - 

> error: cannot parse the debug map for  "/Users/xxx/Library/Developer/Xcode/DerivedData/App-embmpvwoydfvcfdvcodawtdyxjfw/Build/Products/Debug-iphoneos/App.app/PlugIns/AppTests.xctest/AppTests": No such file or directory

**Comment by ohadnav** [comment] 2017-08-07 21:10
Additional info from verbose debugging

> The following build commands failed:
	Ld /Users/ohad/Library/Developer/Xcode/DerivedData/TrueThat-embmpvwoydfvcfdvcodawtdyxjfw/Build/Products/Debug-iphoneos/KIF/KIF.framework/KIF normal arm64
	Ld /Users/ohad/Library/Developer/Xcode/DerivedData/TrueThat-embmpvwoydfvcfdvcodawtdyxjfw/Build/Products/Debug-iphoneos/TrueThat.app/PlugIns/TrueThatTests.xctest/TrueThatTests normal arm64
	GenerateDSYMFile /Users/ohad/Library/Developer/Xcode/DerivedData/TrueThat-embmpvwoydfvcfdvcodawtdyxjfw/Build/Products/Debug-iphoneos/TrueThat.app/PlugIns/TrueThatTests.xctest.dSYM /Users/ohad/Library/Developer/Xcode/DerivedData/TrueThat-embmpvwoydfvcfdvcodawtdyxjfw/Build/Products/Debug-iphoneos/TrueThat.app/PlugIns/TrueThatTests.xctest/TrueThatTests

**Comment by ohadnav** [comment] 2017-08-07 21:21
The problem can be reproduced with: https://github.com/true-that/ios

**Comment by mikelupo** [comment] 2017-08-18 13:25
@justinseanmartin did you get a chance to take a look at this? I'm afraid that I cannot offer assistance with cocoapods as I've never used it.

**Comment by justinseanmartin** [comment] 2017-08-18 20:51
Haven't had a chance yet unfortunately. Have it downloaded, but haven't had time to try it.

**Comment by gorbat-o** [comment] 2017-08-21 10:24
hey, same issue here

**Comment by justinseanmartin** [comment] 2018-02-06 09:57
@gorbat-o @ohadnav - Did you figure out your issue eventually?

Closing this issue for now, as the issue is now 6 months old. Please reactivate if there is still a problem that needs addressing.

**Closed by justinseanmartin** 2018-02-06 09:57 UTC

**Comment by gorbat-o** [comment] 2018-02-06 10:00
Hello,

I was trying to test directly on the phone instead of the simulator,

I mean I guess, because it was a long time ago ^^
