### ISSUE TITLE
I'm experiencing a similar issue with some legacy ObjC code

### ISSUE THREAD

**Issue by JosephWatkins** [kif-framework/KIF#1040] opened 2018-01-17 03:02 UTC
Can anyone assist me in identifying the issue below? I've just began learning swift and I can't seem to figure out how to fix the following code. My app crashes each time I select My Profile, so I assume it's somewhere in here, however, this is inferred due to the following:

Assertion failure in -[UITableView _dequeueReusableCellWithIdentifier:forIndexPath:usingPresentationValues:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3698.33.7/UITableView.m:7883
2018-01-16 21:41:01.168538-0500 Gleamy[4101:1978203] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Attempted to dequeue multiple cells for the same index path, which is not allowed. If you really need to dequeue more cells than the table view is requesting, use the -dequeueReusableCellWithIdentifier: method (without an index path). Cell identifier: cell, index path: <NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}'
*** First throw call stack:
(0x181c3a364 0x180e80528 0x181c3a238 0x1825d57f4 0x18b51a44c 0x18b353570 0x100b53334 0x18b52bac4 0x18b52c028 0x18b50a8ac 0x18b2c133c 0x18b1edf00 0x185c7d998 0x185c81b20 0x185bee36c 0x185c15b90 0x185c169d0 0x181be1edc 0x181bdf894 0x181bdfe50 0x181affe58 0x1839acf84 0x18b25467c 0x100b7d2b8 0x18161c56c)
libc++abi.dylib: terminating with uncaught exception of type NSException

Here's the code I believe is buggy:

```
-(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    if (indexPath.row==0)
    {
        HeaderCell *cell=[tableView dequeueReusableCellWithIdentifier:@"headercell" forIndexPath:indexPath];

   //     NSDictionary *data = @{@"profile_pic":[response objectForKey:@"profile_pic"]  , @"cover_pic":[response objectForKey:@"cover_pic"],  @"follow_count":[response objectForKey:@"follow_count"],  @"following_count":[response objectForKey:@"following_count"]   ,   @"user_name":[response objectForKey:@"user_name"], @"name":[response objectForKey:@"name"],};


        NSMutableDictionary *data= response;

        UITapGestureRecognizer *tapGesture = [[UITapGestureRecognizer alloc] initWithTarget:self  action:@selector(GalleryClicked)];
        tapGesture.numberOfTapsRequired = 1;
        [cell.img_gallery setUserInteractionEnabled:YES];
        [cell.img_gallery addGestureRecognizer:tapGesture];
        
        
        
        UITapGestureRecognizer *viewProfilepic = [[UITapGestureRecognizer alloc] initWithTarget:self  action:@selector(showProfilePic)];
        viewProfilepic.numberOfTapsRequired = 1;
        [cell.img_profilepic setUserInteractionEnabled:YES];
        [cell.img_profilepic addGestureRecognizer:viewProfilepic];
        
        UITapGestureRecognizer *viewcoverpic = [[UITapGestureRecognizer alloc] initWithTarget:self  action:@selector(showCoverPic)];
        viewcoverpic.numberOfTapsRequired = 1;
        [cell.img_coverPic setUserInteractionEnabled:YES];
        [cell.img_coverPic addGestureRecognizer:viewcoverpic];
        

        
        [cell.btn_message addTarget:self action:@selector(myMessages) forControlEvents:UIControlEventTouchUpInside];
        [cell.btn_notification addTarget:self action:@selector(notifications) forControlEvents:UIControlEventTouchUpInside];
        
            [cell setUpHeaderCellWithData:data];
        
        
        if ([data objectForKey:@"profile_pic"])
        {
            if ([[data objectForKey:@"profile_pic"] containsString:@"http"])
                profilPicUrl=[data objectForKey:@"profile_pic"];
            else
                profilPicUrl=@"http://gleamedm.com/reb/img/fans/profile_pic/default.jpg";
        }
        
        
        if ([data objectForKey:@"cover_pic"])
        {
            if ([[data objectForKey:@"cover_pic"] containsString:@"http"])
                coverPicUrl=[data objectForKey:@"cover_pic"];
            
            else
                coverPicUrl=[NSString stringWithFormat:@"http://gleamedm.com/reb/img/fans/cover_pic/%@",[data objectForKey:@"cover_pic"]];
        }
        else
            coverPicUrl=@"http://gleamedm.com/reb/img/fans/cover_pic/default.jpg";
        

        

        return cell;
    }
    else
    {
        int index=(int)indexPath.row-1;    // bcoz 0 is for header
        indexPath=[NSIndexPath indexPathForRow:index inSection:0];
        
        SinglePost *postObj = (SinglePost *)[posts objectAtIndex:index];

        if (postObj.msg_postImgStr .length >0)
        {
            MyProfileDataCell2 *cell=(MyProfileDataCell2*)[tableView dequeueReusableCellWithIdentifier:@"dataCell2" forIndexPath:indexPath];
            
            [cell setupCellWithPostObject:postObj];
            [cell.textView setDelegate: self];
            cell.textView.tag=index;

            
            UITapGestureRecognizer *tapGesture2 = [[UITapGestureRecognizer alloc] initWithTarget:self  action:@selector(Postclicked:)];
            [cell.topView setUserInteractionEnabled:YES];
            [cell.topView addGestureRecognizer:tapGesture2];
            [cell.topView setTag:index];
            
            
            [cell.btn_comment addTarget:self action:@selector(commentClicked:) forControlEvents:UIControlEventTouchUpInside];
            [cell.btn_likeUnlike addTarget:self action:@selector(likeUnlikeClicked:) forControlEvents:UIControlEventTouchUpInside];
            
            cell.btn_likeUnlike.tag=cell.btn_comment.tag=index;
            
            UITapGestureRecognizer *viewcoverpic = [[UITapGestureRecognizer alloc] initWithTarget:self  action:@selector(PostPictureClicked:)];
            viewcoverpic.numberOfTapsRequired = 1;
            [cell.img_messagePic setUserInteractionEnabled:YES];
            [cell.img_messagePic addGestureRecognizer:viewcoverpic];
            [cell.img_messagePic setTag:index];
            
            
            return cell;
        }
        else
        {
            DataCell1 *cell=[tableView dequeueReusableCellWithIdentifier:@"cell" forIndexPath:indexPath];
            [cell setupCellWithPostObject:postObj];
        
            [cell.textView setDelegate: self];
            cell.textView.tag=index;
            
            UITapGestureRecognizer *tapGesture2 = [[UITapGestureRecognizer alloc] initWithTarget:self  action:@selector(Postclicked:)];
            [cell.topView setUserInteractionEnabled:YES];
            [cell.topView addGestureRecognizer:tapGesture2];
            [cell.topView setTag:index];
            
            
            [cell.btn_comment addTarget:self action:@selector(commentClicked:) forControlEvents:UIControlEventTouchUpInside];
            [cell.btn_likeUnlike addTarget:self action:@selector(likeUnlikeClicked:) forControlEvents:UIControlEventTouchUpInside];
        
            cell.btn_likeUnlike.tag=cell.btn_comment.tag=index;
            return cell;
        }
    }
}
```

 Any help is greatly appreciated!

**Comment by justinseanmartin** [comment] 2018-01-18 00:52
Closing as a dupe of issue #1007.

Can you try pointing your KIF at the branch from a PR with a potential fix to see if that works for you? https://github.com/kif-framework/KIF/pull/1020 (mikelupo:fixForIssue1007)

Do you have a small sample project that could be used to reproduce the issue? I've yet to have something that could be used to verify the problem and the fix.

**Closed by justinseanmartin** 2018-01-18 00:52 UTC
