### ISSUE TITLE
nvalid configuration: LRQTestCaseUITests sets both USES_XCTRUNNER and TEST_HOST

### ISSUE THREAD

**Issue by silenceleewq** [kif-framework/KIF#1105] opened 2019-04-19 15:37 UTC
Hello, I have encountered some problems when I use KIF.
First of all, I received an alert which shows "Invalid configuration: LRQTestCaseUITests sets both USES_XCTRUNNER and TEST_HOST" after I config "Bundle Loader" and "Test Host" .

then, I removed this "$(BUILT_PRODUCTS_DIR)/MyApplication.app/MyApplication" from "Test Host", it could run test. but, the program was crash at "UIApplication-KIFAdditions.m", line 119:
`- (NSArray *)windowsWithKeyWindow`
`{`
`    NSMutableArray *windows = self.windows.mutableCopy;`
`    UIWindow *keyWindow = self.keyWindow;`
`    if (![windows containsObject:keyWindow]) {`
`        [windows addObject:keyWindow];`
`    }`
`    return windows;`
`}`

the `windows` is nil, I wonder how to solve it.
thanks for your watching!

**Comment by justinseanmartin** [comment] 2019-04-21 05:35
This is a duplicate of issue #919, but the information included at the very top of the README.md. If you have any ideas of how to make this more clear, would definitely be open to suggestions, as this is a fairly common mistake.

**Closed by justinseanmartin** 2019-04-21 05:35 UTC
