### ISSUE TITLE
deactivateApp(forDuration:) fails on iOS 11

### ISSUE THREAD

**Issue by npark-mozilla** [kif-framework/KIF#1000] opened 2017-08-22 19:28 UTC
On XCode 9 and iOS 11, when deactivateApp(forDuration:) is called, it initially returns to the home screen. When the time is up, it doesn't reinstate the app, but rather it shows the app in the carousel view as seen below:

![screen shot 2017-08-22 at 3 27 08 pm](https://user-images.githubusercontent.com/6930774/29583539-88c63292-874e-11e7-9e47-00beab4def0a.png)

**Comment by justinseanmartin** [comment] 2017-09-25 20:28
Sorry about that! Might need to do a class dump on the iOS 11 UIAutomation framework to see if something has changed.

Personally, I've been avoiding using anything that relies on `UIAutomationHelper`, because it feels brittle and a bit hacky to me to bridge to Apple's UIA framework within KIF. In the cases we need to background the app, we just simulate the appropriate events by calling into the AppDelegate.

If you have time to investigate, would appreciate the help. Not sure when I'll have time to look into this behavior.

**Comment by justinseanmartin** [comment] 2018-01-29 09:59
The callstack where an exception is thrown is here:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 3.1
  * frame #0: 0x000000012bd6521a UIAutomation`-[UIATarget reactivateApp]
    frame #1: 0x000000012bd64f5d UIAutomation`-[UIATarget deactivateAppForDuration:] + 393
    frame #2: 0x000000011bceeb28 KIF Tests - XCTest`-[UIAutomationHelper deactivateAppForDuration:](self=0x00006080002010b0, _cmd="deactivateAppForDuration:", duration=0xb000000000000055) at UIAutomationHelper.m:129
    frame #3: 0x000000011bcee836 KIF Tests - XCTest`+[UIAutomationHelper deactivateAppForDuration:](self=UIAutomationHelper, _cmd="deactivateAppForDuration:", duration=0xb000000000000055) at UIAutomationHelper.m:108
    frame #4: 0x000000011bd0519a KIF Tests - XCTest`-[KIFSystemTestActor deactivateAppForDuration:](self=0x0000608000467340, _cmd="deactivateAppForDuration:", duration=5) at KIFSystemTestActor.m:118
    frame #5: 0x000000011bccc03a KIF Tests - XCTest`-[BackgroundTests testBackgroundApp](self=0x000060400024b520, _cmd="testBackgroundApp") at BackgroundTests.m:38
```

Within the UIAutomation code, it calls `[[[[self.target frontMostApp] appItemScrollView]`, which says that it has no child elements. I don't think there is much we can do about this besides file a radar to Apple, as this is coming from within their UIAutomation code. (This is why I don't like relying on using Apple's opaque test frameworks!) The app switcher entry can be found elsewhere in the accessibility hierarchy though:

```
(lldb) po [[[[[[[[[self target] frontMostApp] elements] objectAtIndex:3] elements] objectAtIndex:1] elements] objectAtIndex:2] label]
Test Host
```

I have a fix for this, but it is pretty gross:
```
- (void)deactivateAppForDuration:(NSNumber *)duration {
    @try {
        [[self target] deactivateAppForDuration:duration];
    }
    @catch(NSException *e) {
        [[[self target] frontMostApp] tap];
    }
}
```

This seems to work for me. If this is blocking anyone and can be confirmed to fix their issues, I'd be happy to put a patch upstream with it.

**Comment by npark-mozilla** [comment] 2018-01-29 22:35
@justinseanmartin Ah, this fix seems to work for me!  It shows the app list, then taps the frontmost one.  Thanks!

**Closed** 2018-02-06 22:44 UTC
