### ISSUE TITLE
KIF version 3.1 added problems to compile with xctool from Facebook

### ISSUE THREAD

**Issue by pmdigregorio** [kif-framework/KIF#524] opened 2014-12-16 15:11 UTC
This is the output:
      -[FAILED_BEFORE TESTS_RAN]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Test did not run: the test bundle stopped running or crashed before the test suite started.

2014-12-16 10:03:11.425 MercadoLibre[73315:381997] KIFTester loaded
2014-12-16 10:03:12.330 MercadoLibre[73315:381997] Application windows are expected to have a root view controller at the end of application launch

We realised that this commit (Swift example) is the problem: https://github.com/kif-framework/KIF/commit/542c940999b5d9a564c140f92c3ea8b73318be1d

**Comment by Gui13** [comment] 2015-01-26 10:10
Bump.. for those interested, using xctool from here: https://github.com/lpios/xctool by calling xctool.sh solves the problem for me.
Until Facebook handles the problem, this could be a solution for those that are stuck.

**Comment by fyruicao** [comment] 2015-02-28 06:42
@Gui13 Why not  send a pull request to xctool?

**Comment by ExtremeMan** [comment] 2015-03-10 17:24
Hey from xctool team!

I investigated this issue yesterday and came to a conclusion that it won't be fixed on xctool side and could be easily fixed on KIF side. Details are below.

### Why xctool is crashing?

As it was told crash happens because of this assert: https://github.com/facebook/xctool/blob/master/Common/DuplicateTestNameFix.m#L55.

### Why is the assert hit?

The assert is hit because the test case is trying to be run which isn't listed in the test suite. In this function https://github.com/facebook/xctool/blob/master/Common/DuplicateTestNameFix.m#L70 internal xctool object is associated with all tests included in the passed test suite. Then this internal object is used to return test `name` and `description`.

But in KIF framework before test suite is run in `+ (void)setUp` (https://github.com/kif-framework/KIF/blob/4cd78488c590ac40946a37df04bb44fc3b5b23a3/Classes/KIFTestCase.m#L71) is called method `performSetupTearDownWithSelector:` (https://github.com/kif-framework/KIF/blob/4cd78488c590ac40946a37df04bb44fc3b5b23a3/Classes/KIFTestCase.m#L81). In that method new test is generated (https://github.com/kif-framework/KIF/blob/4cd78488c590ac40946a37df04bb44fc3b5b23a3/Classes/KIFTestCase.m#L83-L85) just to perform a particular selector. Obviously that "test" is not listed in test suite so xctool knows nothing about it and crashes.

### How to fix?

In my opinion it is not correct way to use `performTest` to perform a selector. By replacing mentioned lines with these:

    KIFTestCase *testCase = [self testCaseWithSelector:selector];
    if ([testCase respondsToSelector:selector]) {
      [testCase performSelector:selector];
    }

the issue is fixed. With the fix all KIF tests were passed for a test project.

We aren't going to fix that in xctool because there is no correct way to do that -- `beforeAll` or `afterAll` selectors called by KIF as tests aren't tests and as a result shouldn't be listed and run as tests.

**Comment by hiltonc** [comment] 2015-03-10 17:49
Please get together and fix this one way or the other :)

**Comment by jmig** [comment] 2015-03-10 17:58
I was looking at this issue and how to fix it. (I had to revert some cool new Functional tests the other day because of this KIF-xctool compatibility issue).

Thanks @ExtremeMan for your explanations! Hopefully KIF maintainers will agree and merge your PR.

**Comment by pmdigregorio** [comment] 2015-03-10 18:01
+1 Thanks @ExtremeMan, I agree with you. I hope this commit https://github.com/kif-framework/KIF/commit/4cd78488c590ac40946a37df04bb44fc3b5b23a3 isn't a blocker

**Comment by phatmann** [comment] 2015-03-10 18:28
@ExtremeMan thanks for the detailed explanation and pull request #589. I will take a look at it now. As long as the current logging behavior is preserved I will merge it in, and we will finally have a fix for this issue!

**Comment by phatmann** [comment] 2015-03-10 19:07
Fixed in #589. Great news!

**Closed by phatmann** 2015-03-10 19:07 UTC

**Comment by hiltonc** [comment] 2015-03-10 19:12
Thank you!
