### ISSUE TITLE
clearAndEnterText:expectedResult: not capitalizing

### ISSUE THREAD

**Issue by colinator** [kif-framework/KIF#1018] opened 2017-10-27 21:37 UTC
Seeing some strange behavior - maybe iOS 11 related?

I've got a UITextField with auto capitalization turned on.

I call `- (void)clearAndEnterText:(NSString *)text expectedResult:(NSString *)expectedResult;`
like so: `clearAndEnterText("another test", expectedResult: "Another Test")`

But it fails. Watching the simulator, I can see that it doesn't actually perform the capitalization (and it looks like it's pasting?).

And here's the weird thing: _sometimes_ it does perform capitalization. Of some words. Completely randomly.

**Comment by mikelupo** [comment] 2017-10-28 00:35
Definitely iOS 11. Apple added new auto punctuation (smart quotes and smart dashes) in this release.
In fact iOS was randomly trying to capitalize the word, “new” in this email.

Autoincorrect will reference your contacts for spelling. You may be able to use that to your advantage?

**Comment by justinseanmartin** [comment] 2017-10-30 08:38
We've globally disabled the autocorrect type behaviors (including capitalization & punctuation) at runtime in our tests and don't explicitly avoid testing it in our code. See #1012 for an example of how we're doing that. My reasoning is that behavior is outside our control and can be changed by a user anyway.

Personally, the text I have KIF enter is what I expect to appear in the field (unless there is a special formatter in our code).

**Comment by justinseanmartin** [comment] 2017-10-30 08:49
Also, if it looks like the text is being pasted, it might be hitting the code path in `enterTextIntoCurrentFirstResponder:fallbackView:` where it calls `setText:`? We have one custom typist in our codebase where this may sometimes happen (though I don't think we ever hit it). Might be worth looking at though.

**Comment by justinseanmartin** [comment] 2018-01-18 03:55
Closing as a dupe of #1012

**Closed by justinseanmartin** 2018-01-18 03:55 UTC
