### ISSUE TITLE
"Please remove uses of SCRCException"

### ISSUE THREAD

**Issue by PatrykKaczmarek** [kif-framework/KIF#586] opened 2015-03-03 18:12 UTC
I'm using KIF with Specta/Expecta in project. Here is podfile which configures my Test Targets:
```
target 'Tests' do
    link_with 'Unit Tests', 'Functional Tests'
    
    pod 'Expecta'
    pod 'KIF'
    pod 'OCMock'
    pod 'OHHTTPStubs'
    pod 'Specta', git: 'https://github.com/specta/specta.git', tag: 'v0.3.0.beta1'
end
```
My spec is extremely easy and looks more or less as follows:
```
SpecBegin(PrefixScreenSpec)

describe(@"on screen", ^{
    describe(@"tapping button", ^{  
        it(@"should show new controller.", ^{
            [tester tapViewWithAccessibilityLabel:@"button"];
        });
    }); 
});
SpecEnd
```

Everything works ok until I change to Xcode 6.3. beta 2. When I run my tests there, code will stop executing [on this line](https://github.com/kif-framework/KIF/blob/master/Additions/UIView-KIFAdditions.m#L402) with log in console:
`Please remove uses of SCRCException!`

I tried to google problem but results of searching aren't satisfying. Although I can use stable Xcode 6.1 I want to inform about possible issue.

**Comment by TBonnin** [comment] 2015-03-04 21:27
Thanks @PatrykKaczmarek 
It looks like a duplicate of https://github.com/kif-framework/KIF/issues/574

**Comment by PatrykKaczmarek** [comment] 2015-03-05 12:44
Agree it's duplicate of #574. I didn't check it in active issues. Sorry for that.

**Closed** 2015-03-09 20:45 UTC
