### ISSUE TITLE
XCTest.framework/XCTest because dependent dylib #12 could not be loaded

### ISSUE THREAD

**Issue by daishuyi** [kif-framework/KIF#1092] opened 2018-10-30 10:20 UTC
<img width="863" alt="image" src="https://user-images.githubusercontent.com/38234719/47711591-858f2980-dc70-11e8-9540-09cbb8a33fa0.png">

**Comment by daishuyi** [comment] 2018-10-30 10:21
How to work it?

**Comment by mikelupo** [comment] 2018-10-30 11:53
This is fixed in Xcode 10.1, but it's still in beta. Your choices are to download the Xcode 10 beta 3, or use Xcode 9.4.1 until Xcode 10.1 is officially released.

**Comment by mikelupo** [comment] 2018-10-30 13:45
Since this is known, I'll go ahead and close this. Reopen if you have the problem in Xcode 10.1 beta or Xcode 9.4.1.

**Closed by mikelupo** 2018-10-30 13:45 UTC

**Comment by justinseanmartin** [comment] 2018-10-30 15:22
Also, duplicate of issue #1084
