### ISSUE TITLE
Not able to run test on Xcode 9.1

### ISSUE THREAD

**Issue by gkrinord** [kif-framework/KIF#1023] opened 2017-11-09 23:46 UTC
I am using XCTest gherkin and KIF to write my integration UI test. It all works fine on Xcode 8.3.3 with KIF 3.5.1
But recently, when I upgraded to Xcode 9.1 and OS 10.12.6, tests are not running, tried with latest KIF 3.6.0 as well. Attaching the logs.

> "2017-11-09 14:45:43.017791-0800 fla-ios[65148:627668] KIFTester loaded
2017-11-09 14:45:44.331537-0800 fla-ios[65148:627668] Could not successfully update network info during initialization.
2017-11-09 14:45:46.113680-0800 fla-ios[65148:627668] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /Users/pair/Library/Developer/CoreSimulator/Devices/AF23FD3F-F6C7-42A6-8B73-FD541D3161F6/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2017-11-09 14:45:46.114132-0800 fla-ios[65148:627668] [MC] Reading from private effective user settings.
> "2017-11-09 14:45:46.466104-0800 fla-ios[65148:627668] Could not successfully update network info during initialization.
Test Suite 'Selected tests' started at 2017-11-09 14:45:46.754
Test Suite 'KIF.framework' started at 2017-11-09 14:45:46.759
Test Suite 'fla-iosIntegrationTests.xctest' started at 2017-11-09 14:45:46.769
Test Suite 'CheckOutFeature' started at 2017-11-09 14:45:46.770
2017-11-09 14:45:47.168701-0800 fla-ios[65148:627668] Could not successfully update network info during initialization.
2017-11-09 14:45:49.308136-0800 fla-ios[65148:627668] [MC] Lazy loading NSBundle MobileCoreServices.framework
2017-11-09 14:45:49.308297-0800 fla-ios[65148:627668] [MC] Loaded MobileCoreServices.framework
2017-11-09 14:45:49.571512-0800 fla-ios[65148:627668] Could not successfully update network info during initialization.
2017-11-09 14:45:49.764486-0800 fla-ios[65148:627668] Could not successfully update network info during initialization.
2017-11-09 14:45:50.291504-0800 fla-ios[65148:627668] [TableView] Setting the background color on UITableViewHeaderFooterView has been deprecated. Please set a custom UIView with your desired background color to the backgroundView property instead.
2017-11-09 14:45:50.295901-0800 fla-ios[65148:627668] [Accessibility] AX ERROR: Could not find my mock parent, most likely I am stale.
2017-11-09 14:45:50.298344-0800 fla-ios[65148:627668] [Accessibility] AX ERROR: Could not find my mock parent, most likely I am stale.
2017-11-09 14:45:50.308019-0800 fla-ios[65148:627668] [TableView] Setting the background color on UITableViewHeaderFooterView has been deprecated. Please set a custom UIView with your desired background color to the backgroundView property instead.
2017-11-09 14:45:50.309790-0800 fla-ios[65148:627668] *** Assertion failure in -[UITableView _dequeueReusableCellWithIdentifier:forIndexPath:usingPresentationValues:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3698.21.8/UITableView.m:7810
<unknown>:0: error: CheckOutFeature : Attempted to dequeue multiple cells for the same index path, which is not allowed. If you really need to dequeue more cells than the table view is requesting, use the -dequeueReusableCellWithIdentifier: method (without an index path). Cell identifier: DepartmentCell, index path: <NSIndexPath: 0x600000a39ac0> {length = 2, path = 0 - 6}
(
	0   CoreFoundation                      0x00000001012e11ab __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000108304f41 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001012e6372 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00000001022df089 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   UIKit                               0x0000000105a086d6 -[UITableView _dequeueReusableCellWithIdentifier:forIndexPath:usingPresentationValues:] + 454
	5   UIKit                               0x0000000105a084dc -[UITableView dequeueReusableCellWithIdentifier:forIndexPath:] + 89
	6   UIKit                               0x000000012972ebc8 -[UITableViewAccessibility dequeueReusableCellWithIdentifier:forIndexPath:] + 285
	7   NBShop                              0x000000010429900d _T06NBShop22CategoryViewControllerC05tableC0So07UITableC4CellCSo0fC0C_10Foundation9IndexPathV12cellForRowAttF + 253
	8   NBShop                              0x0000000104299c8c _T06NBShop22CategoryViewControllerC05tableC0So07UITableC4CellCSo0fC0C_10Foundation9IndexPathV12cellForRowAttFTo + 92
	9   KIF                                 0x000000012681bf0e -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 3822
	10  KIF                                 0x000000012681afe8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 72
	11  KIF                                 0x000000012681b37e -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 862
	12  KIF                                 0x000000012681afe8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 72
	13  KIF                                 0x000000012681b37e -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 862
	14  KIF                                 0x000000012681afe8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 72
	15  KIF                                 0x000000012681b37e -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 862
	16  KIF                                 0x000000012681afe8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 72
	17  KIF                                 0x000000012681b37e -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 862
	18  KIF                                 0x000000012681afe8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 72
	19  KIF                                 0x000000012681b37e -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 862
	20  KIF                                 0x000000012681afe8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 72
	21  KIF                                 0x000000012681b37e -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 862
	22  KIF                                 0x000000012681afe8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 72
	23  KIF                                 0x000000012681b37e -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 862
	24  KIF                                 0x000000012681afe8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 72
	25  KIF                                 0x000000012681b37e -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 862
	26  KIF                                 0x000000012681afe8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 72
	27  KIF                                 0x000000012681b37e -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 862
	28  KIF                                 0x000000012681afe8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 72
	29  KIF                                 0x000000012681b37e -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 862
	30  KIF                                 0x000000012681afe8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 72
	31  KIF                                 0x000000012681b37e -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] + 862
	32  KIF                                 0x000000012681afe8 -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] + 72
	33  KIF                                 0x000000012681a769 -[UIView(KIFAdditions) accessibilityElementWithLabel:accessibilityValue:traits:] + 249
	34  KIF                                 0x00000001268138be -[UIApplication(KIFAdditions) accessibilityElementWithLabel:accessibilityValue:traits:] + 542
	35  KIF                                 0x0000000126811251 +[UIAccessibilityElement(KIFAdditions) accessibilityElementWithLabel:value:traits:fromRootView:error:] + 417
	36  KIF                                 0x00000001268107c2 +[UIAccessibilityElement(KIFAdditions) accessibilityElement:view:withLabel:value:traits:fromRootView:tappable:error:] + 258
	37  KIF                                 0x000000012681067b +[UIAccessibilityElement(KIFAdditions) accessibilityElement:view:withLabel:value:traits:tappable:error:] + 235
	38  KIF                                 0x00000001267f6892 __110-[KIFUITestActor(ConditionalTests) tryFindingAccessibilityElement:view:withLabel:value:traits:tappable:error:]_block_invoke + 114
	39  KIF                                 0x00000001267f3587 -[KIFTestActor tryRunningBlock:complete:timeout:error:] + 167
	40  KIF                                 0x00000001267f67af -[KIFUITestActor(ConditionalTests) tryFindingAccessibilityElement:view:withLabel:value:traits:tappable:error:] + 383
	41  KIF                                 0x00000001267f65ef -[KIFUITestActor(ConditionalTests) tryFindingViewWithAccessibilityLabel:value:traits:tappable:error:] + 175
	42  KIF                                 0x00000001267f618d -[KIFUITestActor(ConditionalTests) tryFindingViewWithAccessibilityLabel:error:] + 109
	43  fla-iosIntegrationTests             0x0000000126640a51 _T023fla_iosIntegrationTests11CommonStepsC23tryFindingViewWithLabelSbSS013accessibilityK0_tF + 257
	44  fla-iosIntegrationTests             0x000000012667ad0d _T023fla_iosIntegrationTests12PopUpsScreenC016tapYesInLocationE2UpyyF + 301
	45  fla-iosIntegrationTests             0x000000012667abbc _T023fla_iosIntegrationTests12PopUpsScreenC14turnOnLocationyyF + 28
	46  fla-iosIntegrationTests             0x0000000126610603 _T023fla_iosIntegrationTests15CheckOutFeatureC9beforeAllyyF + 51
	47  fla-iosIntegrationTests             0x0000000126610644 _T023fla_iosIntegrationTests15CheckOutFeatureC9beforeAllyyFTo + 36
	48  KIF                                 0x00000001267f4c5f +[KIFTestCase performSetupTearDownWithSelector:] + 111
	49  KIF                                 0x00000001267f4bac +[KIFTestCase setUp] + 44
	50  XCTest                              0x00000001257566fd __27-[XCTestSuite performTest:]_block_invoke + 58
	51  XCTest                              0x0000000125756195 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 26
	52  XCTest                              0x0000000125756392 -[XCTestSuite performTest:] + 239
	53  XCTest                              0x000000012575682e __27-[XCTestSuite performTest:]_block_invoke + 363
	54  XCTest                              0x0000000125756195 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 26
	55  XCTest                              0x0000000125756392 -[XCTestSuite performTest:] + 239
	56  XCTest                              0x000000012575682e __27-[XCTestSuite performTest:]_block_invoke + 363
	57  XCTest                              0x0000000125756195 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 26
	58  XCTest                              0x0000000125756392 -[XCTestSuite performTest:] + 239
	59  XCTest                              0x00000001257aef23 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 40
	60  XCTest                              0x0000000125769a0e -[XCTestObservationCenter _observeTestExecutionForBlock:] + 475
	61  XCTest                              0x00000001257aedc2 -[XCTTestRunSession runTestsAndReturnError:] + 281
	62  XCTest                              0x0000000125745e87 -[XCTestDriver runTestsAndReturnError:] + 314
	63  XCTest                              0x00000001257a6a64 _XCTestMain + 619
	64  CoreFoundation                      0x000000010128418c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	65  CoreFoundation                      0x000000010126896b __CFRunLoopDoBlocks + 203
	66  CoreFoundation                      0x0000000101268144 __CFRunLoopRun + 1300
	67  CoreFoundation                      0x00000001012679b9 CFRunLoopRunSpecific + 409
	68  GraphicsServices                    0x000000010dbe29c6 GSEventRunModal + 62
	69  UIKit                               0x00000001058c45e8 UIApplicationMain + 159
	70  fla-ios                             0x00000001001c4344 main + 500
	71  libdyld.dylib                       0x0000000109ea8d81 start + 1
)
Test Suite 'CheckOutFeature' failed at 2017-11-09 14:45:50.391.
	 Executed 0 tests, with 1 failure (1 unexpected) in 0.000 (3.620) seconds`"

**Comment by justinseanmartin** [comment] 2017-11-11 00:11
This is a duplicate of #1007. Please take a look there. Would you mind picking up the proposed fix in #1020 locally and see how that works for you?

**Closed by justinseanmartin** 2017-11-11 00:11 UTC
