### ISSUE TITLE
Fallback code when tests fail

### ISSUE THREAD

**Issue by ristkof** [kif-framework/KIF#1056] opened 2018-02-16 09:02 UTC
My setup is such that (for the majority of tests) I login and logout a user on every test of my app.

As a consequence, if one test fails, the tests that follow will fail as well, as they are trying to login while the app is left in a state with the user still logged in.

Do you know of any way to have some fallback code when a test fails? I would try to log out the user there, and then maybe the following tests would sometimes still succeed, and it would save me some test runs.

**Comment by mikelupo** [comment] 2018-02-16 11:56
Hi Kristof, 
Thanks for using KIF. 

The issue you're reporting does not seem to be a KIF issue, but rather how you're constructing your test cases for resiliency. I have the same issue with my UI tests. Consider the use of beforeEach, afterEach, beforeAll and afterAll. I use my logout method there.
These methods run (as they are aptly named). You could have a method afterEach that performs your log out. Being on iOS you can force a transition back to the logout page from anywhere in the app to cover cases where the test left the app on an unexpected UI. I'd suggest that you have a talk with one of your team developers on how to do that if you need assistance.
I hope this helps.

For the future, you might consider searching/posting questions like this to stackoverflow. You'll have a broader reach.

I'll close this for now. If I'm wrong, and you've determined that the problem is with KIF code itself, please reopen and reiterate your issue for our understanding. We're happy to help.

Thanks again!

**Closed by mikelupo** 2018-02-16 11:56 UTC

**Comment by justinseanmartin** [comment] 2018-02-16 21:10
If the app is constructed in such a way that it can be entirely torn down and have a new main view controller and app delegate set up from scratch, you can ensure that there is a clean app state between each individual test.

There unfortunately isn't a way to stop / wipe / launch the app from within the KIF framework, as it all runs inside of you application's process space.
